---
apiVersion: v1
kind: application
metadata:
  name: devtest.remote-caller
  commType: http
spec:
  services:
    - serviceName: remote-caller
      components:
        - componentName: remote-caller
          imageType: docker
          imageName: rc-local
          httpPort: 10002
          interfaces:
            - interfaceName: context1
              interfaceType: http
              upstreamPath: /test
              visiblity: external
              accessList:
                - app@client
            - interfaceName: remote-caller-network
              interfaceType: network
              interfacePort: 10007
              scheme: udp
              visiblity: external
              accessList:
                - app@client
          resourceProfiles:
            - resourceProfileName: default
              memory: 1024
              cpu: 1
          defaultResourceProfile: default
